spring:
  application:
    # 指定服务名称
    name: sb-test

  # 由 spring cloud config加载配置
  #profiles:
    #active: dev

  jackson:
    default-property-inclusion: non_null

management:
  # actuator安全认证(手动刷新yml配置文件需关闭)
  security:
    enabled: false

# 手动刷新yml配置文件: POST application/x-www-form-urlencoded表单请求本项目ip:port/refresh
# 自动刷新yml配置文件:
# 1、借助与git的webhook(web钩子, 多个项目需配置多个钩子) http://ip:port/refresh
# 2、Spring Cloud Bus 消息总线同步集群微服务