spring:
  application:
    # 指定服务名称
    name: sb-test

  # 由 spring cloud config加载配置
  #profiles:
    #active: dev

  jackson:
    default-property-inclusion: non_null

management:
  # actuator安全认证(用于暴露MQ的端点)
  security:
    enabled: false